export const DOCTORS_DATA = [
    {
        name: "سناء صميدة",
        phone: "+912222222",
        email: "google@gmail.com",
        sex: "أنثى",
        description: "أخصائية أمراض نساء وولادة",
        //rating: "5/5",
        role: "doctors",
        img: "sana.jpg",
        clinic: 3,
        specialization: 5,
    },
    {
        name: "ليلى الحبشي",
        phone: "+218564789",
        email: "laila@gmail.com",
        sex: "أنثى",
        description: "أخصائية أمراض نساء وولادة",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 2,
        specialization: 5,
    },
    {
        name: "وليد العربي",
        phone: "+21822222",
        email: "walid@gmail.com",
        sex: "ذكر",
        description: "أخصائي جراحه العظام والإصابات الرياضية,رئيس قسم العظام بمشفى غريان الطبي",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 1,
        specialization: 3,
    },
    {
        name: "هيثم نورالدين الشامس",
        phone: "+21811111",
        email: "haitem@gmail.com",
        sex: "ذكر",
        description: "ماجستير جراحه عامه ومناظير من جامعه الزقازيق جمهوريه مصر العربيه ,خبره اكتر من عشره سنوات في مجال الجراحه العامه وجراحه الاطفال وجراحه المناظير,عضو هيئة تدريس في كليه الطب البشري جامعه غريان",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 1,
        specialization: 3,
    },
    {
        name: "هاجر فتحي الصالح",
        phone: "0924262536",
        email: "hajer@gmail.com",
        sex: "أنثى",
        description: "دكتورة أطفال",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 3,
        specialization: 2,
    },
    {
        name: "عواطف بركات",
        phone: "091222222",
        email: "awatif@gmail.com",
        sex: "أنثى",
        description: "بكالوريوس طب وجراحة عامة سنة 2007 جامعة غريان, ماستر أبحاث من جامعة ليل 2 جمهورية فرنسا سنة 2014,دبلوم في أمراض العيون والتهاباتها من جامعة باريس 7 السوربون  سنة 2015, خبرة بمستشفيات فرنسا من سنة 2014-2016",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 2,
        specialization: 1,
    },
    {
        name: "صهيب العاني",
        phone: "091555555",
        email: "suhaib@gmail.com",
        sex: "ذكر",
        description: "متدرب لدى المجلس العربي للإختصاصات الطبية في تخصص طب وجراحة العيون",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 3,
        specialization: 1,
    },
    {
        name: "أماني الأسود",
        phone: "091111111",
        email: "amani@gmail.com",
        sex: "أنثى",
        description:"أمراض جلدية و تناسلية و طب التجميل",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 1,
        specialization: 4,
    },
    {
        name: "أسماء الهاشمي",
        phone: "091666666",
        email: "asma@gmail.com",
        sex: "أنثى",
        description:"دكتورة أسنان",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 1,
        specialization: 6,
    },
 
]