export const DOCTORS_DATA = [
    {
        name: "سناء صميدة",
        phone: "+912222222",
        email: "google@gmail.com",
        sex: "أنثى",
        description: "أخصائية أمراض نساء وولادة",
        //rating: "5/5",
        role: "doctors",
        img: "sana.jpg",
        clinic: 1,
        specialization: 3,
    },
    {
        name: "ليلى الحبشي",
        phone: "+218564789",
        email: "laila@gmail.com",
        sex: "أنثى",
        description: "أخصائية أمراض نساء وولادة",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 2,
        specialization: 1,
    },
    {
        name: "هيثم الشامس",
        phone: "+21111111",
        email: "haitem@gmail.com",
        sex: "ذكر",
        description: "أخصائية أمراض نساء وولادة",
        //rating: "5/5",
        role: "doctors",
        img: "Drama.png",
        clinic: 2,
        specialization: 2,
    },
 
]